# Generated by Django 5.1.7 on 2025-04-06 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_type', models.CharField(choices=[('REG', 'Regular Savings'), (
                    'FIX', 'Fixed Deposit'), ('TAR', 'Target Savings')], max_length=3)),
                ('opening_date', models.DateField(auto_now_add=True)),
                ('current_balance', models.DecimalField(
                    decimal_places=2, default=0, max_digits=15)),
                ('interest_rate', models.DecimalField(
                    decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[
                 ('DEP', 'Deposit'), ('WTH', 'Withdrawal'), ('INT', 'Interest')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('account', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='accounts.savingsaccount')),
                ('processed_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
