# Generated by Django 5.1.7 on 2025-04-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_type',
            field=models.CharField(choices=[('REG', 'Regular Savings'), ('FIX', 'Fixed Deposit'), ('TAR', 'Target Savings'), ('ADJ', 'Adjustment')], max_length=3),
        ),
    ]
