# Generated by Django 5.2 on 2025-04-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
