# Generated by Django 5.2.4 on 2025-08-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], default='cash', max_length=20),
        ),
    ]
