# Generated by Django 5.2 on 2025-06-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_savingsaccount_account_type'),
        ('members', '0007_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='savingsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='group_logos/')),
                ('monthiy_target', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('meeting_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.savingsgroup')),
            ],
            options={
                'unique_together': {('group', 'member')},
            },
        ),
    ]
