# Generated by Django 5.1.7 on 2025-08-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savingsgroup_groupmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMember',
        ),
    ]
