# Generated by Django 5.2 on 2025-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_loan_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
