# Generated by Django 5.2 on 2025-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_member_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
