# Generated by Django 5.2 on 2025-06-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loan',
        ),
    ]
