# Generated by Django 5.2 on 2025-06-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment_reference_alter_loan_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='User_id',
            new_name='User',
        ),
    ]
