# Generated by Django 5.2 on 2025-06-01 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_user_id_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='User',
        ),
        migrations.AddField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='users.member'),
        ),
    ]
