# Generated by Django 5.2 on 2025-06-02 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_loan_user_loan_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_method',
            field=models.CharField(default=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money')], max_length=50),
        ),
    ]
