# Generated by Django 5.2.4 on 2025-08-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_loan_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='user',
        ),
        migrations.DeleteModel(
            name='loan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
    ]
